packages:
  - 'apps/*'
  - 'contracts/*'
  - 'libs/*'
  - 'platform/*'
  - 'tools/*'

allowBuilds:
  nx: true

overrides:
  axios: 1.18.0
  brace-expansion: 5.0.7

catalogMode: strict

cleanupUnusedCatalogs: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - newland-erp

strictDepBuilds: true
