[versions]
archunit = "1.4.2"
checkstyle = "13.8.0"
cyclonedx = "3.3.0"
detekt = "1.23.8"
flyway = "13.0.0"
gradle-versions = "0.54.0"
jooq = "3.21.5"
junit = "6.1.2"
ktlint = "1.8.0"
owasp-dependency-check = "12.2.2"
postgresql = "42.7.11"
spring-boot = "4.1.0"
spring-modulith = "2.1.0"
springdoc = "3.0.3"
spotless = "8.8.0"
testcontainers = "2.0.5"

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
jooq = { module = "org.jooq:jooq", version.ref = "jooq" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
springdoc-openapi-webmvc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdoc" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core", version.ref = "spring-modulith" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test", version.ref = "spring-modulith" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }

[plugins]
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dependency-check = { id = "org.owasp.dependencycheck", version.ref = "owasp-dependency-check" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
