build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

complexity:
  LongMethod:
    active: true
    threshold: 40
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
